### ISSUE TITLE
nc/i-metric-joint-k-5-d-3.nc' data is not downlaoding

### ISSUE THREAD

**Issue by ronygolderku** [so-wise/so-fronts#3]
Hi,
When, I am using trying to run this `python3 main.py`

it shows the error like 

high
'mpl_params'  0.00060 s

settings:
 cst.EXAMPLE_TIME_INDEX 40 cst.SEED 10
high
'mpl_params'  0.00038 s

Traceback (most recent call last):
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 209, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 55, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/ubuntu/fronts/nc/i-metric-joint-k-5-d-3.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'cc23bfcc-b404-4b78-9197-6574972c55b7']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    mf.make_all_figures()
  File "/home/ubuntu/fronts/src/time_wrapper.py", line 24, in timed
    result = method(*args, **kw)
  File "/home/ubuntu/fronts/src/make_figures.py", line 57, in make_all_figures
    ds = xr.open_dataset(cst.DEFAULT_NC)
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/api.py", line 541, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 578, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 382, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 329, in __init__
    self.format = self.ds.data_model
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 391, in ds
    return self._acquire()
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 385, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/ubuntu/fronts/env/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 197, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/ubuntu/fronts/env/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 215, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2469, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2028, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/fronts/nc/i-metric-joint-k-5-d-3.nc'

The thing is that, i-metric-joint-k-5-d-3.nc file is not downloaded when I downloaded the bsose data. 
Could you please it?

Best regards,

**Comment by sdat2** [comment]
Hi, thanks a lot for getting in touch, I'm sorry about this error message

**Comment by sdat2** [comment]
Could you let me know if you ran the command `python3 src/models/batch_i_metric.py`. I'm a little hazy on the details, but I think this is the step when this file is created

**Comment by ronygolderku** [comment]
When I ran this command "(/home/ubuntu/fronts/env) ubuntu@indian-ocean:~/fronts$ `python3 src/models/batch_i_metric.py`
output shows that a NC file was created( bold letters). That means, it only creates a single nc file named `interp.nc` instead of `i-metric-joint-k-5-d-3.nc` file.

_The output:_
going to save to:  **/home/ubuntu/fronts/nc/interp.nc**

**Comment by sdat2** [comment]
Hey, thanks for getting back in touch so quickly. I was having a look back at that script: 
<https://github.com/so-wise/so-fronts/blob/main/src/models/batch_i_metric.py>
(which is pretty badly documented, apologies). 

The function `merge_and_save` should save the netcdfs using <https://github.com/so-wise/so-fronts/blob/main/src/data_loading/io_names.py> opening from `io.return_folder` and then saving to `io.return_name`. I think an issue I might have created in the repository is that it saves to `GWS_DATA_DIR` which is set to the particular HPC I was using rather than a generic default.

Thanks for spotting this, I will make a pull request. A quick solution might be to edit `src.constants` but I should test that.

**Comment by ronygolderku** [comment]
Thanks for your kind reply. and no need to apologize. I want to bring your attention to rerunning the whole script and updating the code because some modules have been updated. Specifically, I had to install `seaborn` separately even though I activated the entire environment.
